// ============================================================
//  Ask Sherwin — grounding knowledge base for the LLM proxy
// ============================================================
//
//  This is the SOURCE OF TRUTH the model is grounded on. It mirrors the
//  front-end's src/data/chatData.js QA_DATASET — keep the two in sync.
//  (Kept as a separate copy because the Worker deploys independently of
//  the React app.)
//
//  With only ~50 short entries we do NOT need a vector DB / RAG: the whole
//  set is pasted into the system prompt as grounding context and cached.
// ============================================================

export const QA_DATASET = [
  { id: 1, category: 'Background & Overview', question: 'Who are you and what do you do?', answer: "I'm Sherwin Tang, an AI/Applied Machine Learning Engineer and Full-Stack Software Engineer based in Singapore. I have 7+ years of professional experience, including 4+ years building production-grade systems at scale. I'm currently pursuing an NUS MTech in Artificial Intelligence Systems and specialize in building LLM/RAG applications, full-stack development, and platform engineering." },
  { id: 2, category: 'Background & Overview', question: "What's your professional background?", answer: "I started as a full-stack software engineer with expertise in microservices, Kubernetes, and CI/CD pipelines. Over 7+ years, I've progressed from an individual contributor to a Team Lead role at OCBC Bank, managing cross-border development teams. I'm now expanding into AI and machine learning through formal education and hands-on project experience." },
  { id: 3, category: 'Background & Overview', question: 'What are your main interests?', answer: "I'm passionate about explainable, reliable AI for real-world and safety-critical applications. I'm particularly interested in combining symbolic reasoning with neural approaches, building trustworthy AI systems, and applying generative AI to solve practical problems in healthcare, finance, and operations." },
  { id: 4, category: 'Current Role', question: 'Tell me about your current role at OCBC Bank.', answer: "I'm a Software Engineer and Team Lead in the Trade Finance Squad at OCBC Bank since October 2021. I lead the migration from monolithic to microservices architecture, manage a cross-border development team across 20+ microservices, and translate business and regulatory requirements into compliant solutions. I've also spearheaded the launch of Trade Finance services in Vietnam and led the development of key products like Export Documentary Collection." },
  { id: 5, category: 'Current Role', question: 'What major achievements have you had at OCBC?', answer: "Key achievements include: leading a monolithic-to-microservices migration that improved system efficiency by ~50% and reduced operational costs by ~20%, managing 20+ microservices with a cross-border team, launching Trade Finance services in Vietnam (increasing transaction volume by ~20%), deploying the Export Documentary Collection product with a fully online application channel, maintaining 100% compliance with business and regulatory requirements, and executing critical technical upgrades like Kafka broker upgrades and disaster-recovery simulations." },
  { id: 6, category: 'Current Role', question: 'What technologies do you work with at OCBC?', answer: "At OCBC, I work with microservices architecture, Kubernetes, Apache Kafka, CI/CD tooling (SonarQube, BlackDuck), Oracle and PostgreSQL databases, Jenkins, ControlM, Git, and a range of full-stack technologies. I also work across data processing, data analysis, and infrastructure for trade finance applications." },
  { id: 7, category: 'Previous Experience', question: 'What was your role at SMRT Trains?', answer: "From July 2018 to July 2021, I was a Senior Executive for Strategic Planning & Digital Transformation at SMRT Trains. I led the development of a Kaizen engagement portal to boost employee-driven process improvements, built Power BI dashboards for senior management visibility, digitalized maintenance approval workflows (reducing approval time from 6 days to 1 day and cutting paper usage by ~75%), and ensured KPI accuracy in regulatory reports." },
  { id: 8, category: 'AI/ML Projects', question: 'Tell me about WellnessBot.', answer: "WellnessBot is a home-based, explainable clinical decision-support assistant for post-arthroscopic knee rehabilitation. It's built on a neuro-symbolic architecture combining a knowledge graph and rule-based reasoning with a constrained RAG/LLM layer. This ensures all clinical decisions remain deterministic, transparent, and auditable rather than relying on an opaque LLM. I designed the informed search planner, orchestrated end-to-end pipeline integration, built the Streamlit UI, and implemented comprehensive error handling and testing." },
  { id: 9, category: 'AI/ML Projects', question: 'What was your approach to building WellnessBot?', answer: "I took a neuro-symbolic approach combining symbolic reasoning with neural networks. The system uses a knowledge graph and rule-based engine to ensure deterministic, auditable decisions, with a constrained RAG/LLM layer for natural language. I designed an informed search planner to generate safe, phase-appropriate rehabilitation recommendations, orchestrated end-to-end integration across all components, and built a user-friendly Streamlit interface with robust error handling." },
  { id: 10, category: 'AI/ML Projects', question: "What's the tech stack for WellnessBot?", answer: 'WellnessBot uses Python, OpenAI API, RAG (Retrieval-Augmented Generation), knowledge graphs, rule-based reasoning, and Streamlit for the user interface. The system integrates symbolic knowledge representation with generative AI to balance explainability with natural language capability.' },
  { id: 11, category: 'AI/ML Projects', question: 'Describe your RAG Q&A System project.', answer: 'I built an end-to-end RAG pipeline using LangChain that answers document and FAQ-grounded queries (course enrollment, schedules, funding eligibility) from a custom knowledge base. The system ingests PDFs and CSVs, generates embeddings using Hugging Face sentence-transformers, indexes them in Pinecone for semantic retrieval, and uses LangChain RetrievalQA chains to provide grounded answers that reduce hallucination.' },
  { id: 12, category: 'AI/ML Projects', question: 'What was unique about your RAG project?', answer: 'The project demonstrated end-to-end RAG pipeline implementation with a practical twist: I integrated and compared two interchangeable LLM backends—a local Hugging Face Transformers model (TinyLlama 1.1B-Chat) and OpenAI API (GPT-3.5)—weighing tradeoffs between cost, latency, and answer quality. This shows my ability to optimize AI systems for different deployment constraints.' },
  { id: 13, category: 'Technical Skills', question: 'What programming languages do you know?', answer: "I'm proficient in Python, Java, JavaScript, HTML, and CSS. Python is my primary language for AI/ML work, while Java and JavaScript support my full-stack development background." },
  { id: 14, category: 'Technical Skills', question: 'What are your web and full-stack skills?', answer: "I have hands-on experience with React.js for frontend development, Node.js for backend, Streamlit for rapid prototyping, and Spring/Spring Boot frameworks. I'm comfortable building REST APIs, microservices, and full-stack applications from concept to production." },
  { id: 15, category: 'Technical Skills', question: "What's your cloud and DevOps expertise?", answer: "I have deep expertise in Kubernetes, OpenShift, Helm, CI/CD pipelines (Jenkins, SonarQube, BlackDuck), Git/GitHub, Apache Kafka, ControlM, and Unix. I've led large-scale infrastructure modernization projects including microservices migration and system resilience upgrades." },
  { id: 16, category: 'Technical Skills', question: 'What databases have you worked with?', answer: "I have hands-on experience with Oracle and PostgreSQL databases. I've worked on data modeling, optimization, and integration as part of my full-stack development and platform engineering roles." },
  { id: 17, category: 'AI/ML Skills', question: 'What AI and machine learning frameworks do you use?', answer: "I work with LangChain for LLM orchestration, Hugging Face Transformers and sentence-transformers for NLP, PyTorch and TensorFlow for deep learning, scikit-learn and Pandas for data processing, and vector databases like Pinecone for RAG. I'm also experienced with OpenAI APIs for generative AI applications." },
  { id: 18, category: 'AI/ML Skills', question: "What's your experience with RAG and LLMs?", answer: "I have hands-on experience building Retrieval-Augmented Generation (RAG) systems using LangChain, vector databases (Pinecone), and LLMs. I understand prompt engineering, embedding models, retrieval strategies, and techniques to reduce hallucination. I've also worked with both local models (TinyLlama) and API-based models (OpenAI GPT-3.5)." },
  { id: 19, category: 'AI/ML Skills', question: "What's your expertise in neuro-symbolic AI?", answer: 'I have practical experience combining neural networks with symbolic reasoning. In WellnessBot, I integrated knowledge graphs, rule-based systems, and constrained RAG/LLM components to ensure explainability and determinism. This approach is particularly valuable for safety-critical applications like healthcare where transparency and auditability are essential.' },
  { id: 20, category: 'AI/ML Skills', question: 'Tell me about your NLP and embeddings work.', answer: "I've implemented sentence-transformer embeddings (all-mpnet-base-v2) for semantic similarity and retrieval. My RAG project involved chunking documents, generating embeddings, and using cosine-similarity for retrieval. I understand embedding quality, dimensionality, and their impact on RAG system performance." },
  { id: 21, category: 'AI/ML Skills', question: 'What AI-assisted development tools do you use?', answer: 'I actively use Claude and Devin for AI-assisted development. These tools help me accelerate coding, debugging, and exploring new concepts, enhancing my productivity in both traditional software engineering and AI/ML projects.' },
  { id: 22, category: 'Education', question: 'What are you studying currently?', answer: "I'm pursuing a Master of Technology in Artificial Intelligence Systems (part-time) at the National University of Singapore, starting July 2025. This program is giving me deeper theoretical and practical knowledge in AI/ML to complement my professional engineering background." },
  { id: 23, category: 'Education', question: 'What are your core AI modules?', answer: 'My core modules include Intelligent Reasoning Systems, Pattern Recognition Systems, and other advanced AI topics. Through these, I\'m gaining hands-on experience with ML algorithms, neural networks, computer vision, and NLP through applied projects like WellnessBot.' },
  { id: 24, category: 'Education', question: 'What certifications have you completed?', answer: "I've completed several NUS certifications: Cognitive Systems (Apr 2026), Reasoning Systems (Apr 2026), Machine Reasoning (Mar 2026), Intelligent Sensing and Sense Making (Nov 2025), Pattern Recognition and Machine Learning Systems (Nov 2025), and Problem Solving using Pattern Recognition (Sep 2025)." },
  { id: 25, category: 'Education', question: "What's your undergraduate background?", answer: 'I completed a B.Eng. (Honours) in Materials Science & Engineering from the National University of Singapore (Aug 2014 – May 2018). This technical foundation equipped me with strong problem-solving and analytical skills that have served me well in software engineering and AI/ML.' },
  { id: 26, category: 'Soft Skills', question: 'What leadership experience do you have?', answer: "As Team Lead at OCBC, I've led cross-border development teams spanning Singapore and China across 20+ microservices. I manage team coordination, facilitate Agile delivery, and ensure alignment between engineering and business stakeholders. I've successfully increased project delivery throughput while maintaining high quality and compliance standards." },
  { id: 27, category: 'Soft Skills', question: 'How do you work cross-functionally?', answer: 'I partner closely with Product Owners, UX Designers, and Business Analysts to translate business and regulatory requirements into delivered solutions. My background in both engineering and digital transformation has taught me to bridge technical and non-technical perspectives, ensuring solutions are both technically sound and business-aligned.' },
  { id: 28, category: 'Soft Skills', question: "What's your approach to rapid POCs and MVPs?", answer: "I'm proven at taking ideas from concept to working software through rapid POCs, MVPs, and end-to-end integration. I combine technical depth with pragmatism, using tools like Streamlit for quick prototyping while ensuring robust, production-ready architectures for scaled deployment." },
  { id: 29, category: 'Methodology & Practices', question: 'What software engineering practices do you follow?', answer: "I follow Agile and Scrum methodologies, practice test-driven development, and implement comprehensive integration testing. I'm experienced with CI/CD pipelines, version control, code quality tools (SonarQube, BlackDuck), and infrastructure-as-code with Kubernetes and Helm." },
  { id: 30, category: 'Methodology & Practices', question: 'Tell me about your microservices experience.', answer: "I've led a major migration from monolithic architecture to microservices at OCBC, improving system efficiency by ~50% and reducing operational costs by ~20%. I manage 20+ microservices, handle API design, service communication, data consistency, and operational concerns like monitoring and resilience." },
  { id: 31, category: 'Key Achievements', question: "What's your proudest professional achievement?", answer: 'Leading the monolithic-to-microservices migration at OCBC is a significant achievement—it improved system efficiency by ~50%, reduced operational costs by ~20%, and enabled faster, more independent team delivery. Combined with launching Trade Finance services in Vietnam and achieving 100% regulatory compliance, it demonstrates my ability to drive technical transformation with real business impact.' },
  { id: 32, category: 'Key Achievements', question: 'How did you impact transaction volume in Vietnam?', answer: 'I spearheaded the launch of Trade Finance services in Vietnam, which enabled online applications and increased transaction volume by approximately 20%. This involved coordinating across teams, ensuring regulatory compliance for a new market, and delivering a robust, scalable solution.' },
  { id: 33, category: 'Key Achievements', question: 'What digital transformation did you lead at SMRT?', answer: 'At SMRT, I directed digitalization of maintenance approval workflows, reducing approval time from 6 days to 1 day and cutting paper usage by approximately 75%. I also built a Kaizen engagement portal that significantly increased employee-driven process-improvement initiatives, demonstrating how technology can improve operational efficiency.' },
  { id: 34, category: 'Problem-Solving', question: 'How do you approach complex technical problems?', answer: 'I break down complex problems into manageable components, identify root causes, and design solutions balancing technical excellence with practical constraints. I leverage both theoretical knowledge (from my AI studies) and hands-on experience. For safety-critical systems like WellnessBot, I ensure solutions are explainable and auditable.' },
  { id: 35, category: 'Problem-Solving', question: 'How do you handle system reliability and resilience?', answer: "I've executed critical technical upgrades including Kafka broker upgrades, data-migration exercises, and disaster-recovery simulations. I implement proper error handling, edge-case management, fallback logic, and comprehensive testing. I understand that production systems require not just functionality but reliability, monitoring, and recovery mechanisms." },
  { id: 36, category: 'Project Delivery', question: 'How do you ensure project delivery?', answer: "I combine Agile methodology with clear communication across stakeholders. At OCBC, I've consistently translated business requirements into delivered solutions with 100% compliance. I track progress through sprint planning, retrospectives, and data-driven metrics. For complex projects, I break them into phases and ensure continuous validation." },
  { id: 37, category: 'Project Delivery', question: "What's your experience with regulatory compliance?", answer: "At OCBC, I've maintained a 100% compliance record across business and regulatory requirements in trade finance. I understand the importance of documentation, auditability, and validation in regulated industries, which directly influenced my approach to building explainable AI systems." },
  { id: 38, category: 'Technologies & Tools', question: "What's your experience with containerization and orchestration?", answer: "I have extensive experience with Kubernetes and OpenShift for container orchestration, Helm for package management, and containerized microservices. I've managed large-scale deployments and handled operational concerns like scaling, updates, and resource management." },
  { id: 39, category: 'Technologies & Tools', question: 'Tell me about your CI/CD experience.', answer: "I've worked with Jenkins for pipeline automation, SonarQube for code quality analysis, and BlackDuck for security scanning. I understand the importance of automated testing, continuous integration, and reliable deployment practices to maintain system quality and reduce manual errors." },
  { id: 40, category: 'Technologies & Tools', question: 'What data processing tools have you used?', answer: "I'm proficient with Pandas for data manipulation and analysis, scikit-learn for machine learning, and have worked with Apache Kafka for event streaming. I understand data pipelines, transformations, and the role of data in driving system decisions." },
  { id: 41, category: 'Interests & Vision', question: 'What excites you most about AI?', answer: "I'm excited about building explainable, reliable AI systems for real-world applications, especially in safety-critical domains like healthcare. The combination of symbolic reasoning and neural networks offers a path to AI that's both powerful and trustworthy—I'm passionate about making this a reality." },
  { id: 42, category: 'Interests & Vision', question: "What's your vision for the future of AI in enterprise?", answer: 'I believe enterprises need AI systems that are not just powerful but explainable, auditable, and aligned with regulatory requirements. The future lies in hybrid approaches combining symbolic reasoning with neural networks, ensuring AI enhances human decision-making while maintaining transparency and control.' },
  { id: 43, category: 'Interests & Vision', question: 'How do you stay updated with technology trends?', answer: 'I actively pursue continuous learning through formal education (MTech in AI Systems), hands-on projects, and engagement with AI tools like Claude and Devin. I read research papers, experiment with new frameworks, and apply emerging techniques to real-world problems.' },
  { id: 44, category: 'Collaboration & Teamwork', question: 'How do you approach mentoring and knowledge sharing?', answer: "As a Team Lead, I believe in clear communication and knowledge sharing across the team. I help team members understand complex systems, explain technical decisions, and support their growth. My ability to translate between technical and business perspectives helps the team understand the 'why' behind projects." },
  { id: 45, category: 'Collaboration & Teamwork', question: 'How do you manage across geographical teams?', answer: 'At OCBC, I manage a cross-border team spanning Singapore and China across 20+ microservices. This requires clear async communication, well-documented processes, and strong Agile practices. I ensure alignment through regular standups, sprint planning, and maintaining a single source of truth for team information.' },
  { id: 46, category: 'Career Journey', question: "What's the arc of your career?", answer: "I've progressed from a full-stack software engineer with deep platform engineering expertise to a Team Lead managing complex microservices systems. Now I'm expanding into AI/ML through formal education and hands-on projects, combining my engineering rigor with emerging AI capabilities to build reliable, explainable AI systems." },
  { id: 47, category: 'Career Journey', question: 'What drove your transition to AI?', answer: 'My engineering background taught me the importance of reliability, explainability, and production-grade systems. As AI becomes more prevalent, I wanted to bring these principles to the AI space. I\'m particularly motivated by the potential to build trustworthy AI for high-stakes domains like healthcare.' },
  { id: 48, category: 'Languages', question: 'What languages do you speak?', answer: "I'm a native English and Chinese speaker. This multilingual ability helps me communicate effectively in diverse, international teams—particularly valuable in my cross-border role at OCBC." },
  { id: 49, category: 'Location & Contact', question: 'Where are you based?', answer: "I'm based in Singapore and am a Singapore citizen. I'm open to remote opportunities and have experience working with distributed, cross-border teams." },
  { id: 50, category: 'Summary', question: 'How would you describe yourself in one sentence?', answer: "I'm a full-stack engineer with 7+ years of production-grade experience who's passionate about building explainable, reliable AI systems by combining symbolic reasoning with neural networks." },
];

// Build the grounding block that gets pasted into the system prompt.
export function buildKnowledgeBlock() {
  return QA_DATASET.map(
    (e) => `Q: ${e.question}\nA: ${e.answer}`
  ).join('\n\n');
}
